// Code generated by MockGen. DO NOT EDIT.
// Source: disk.go
//
// Generated by this command:
//
//	mockgen -source=disk.go -destination=disk/mock_disk.go -package=disk -mock_names=Disk=MockDisk
//

// Package disk is a generated GoMock package.
package disk

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDisk is a mock of Disk interface.
type MockDisk struct {
	ctrl     *gomock.Controller
	recorder *MockDiskMockRecorder
	isgomock struct{}
}

// MockDiskMockRecorder is the mock recorder for MockDisk.
type MockDiskMockRecorder struct {
	mock *MockDisk
}

// NewMockDisk creates a new mock instance.
func NewMockDisk(ctrl *gomock.Controller) *MockDisk {
	mock := &MockDisk{ctrl: ctrl}
	mock.recorder = &MockDiskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisk) EXPECT() *MockDiskMockRecorder {
	return m.recorder
}

// Free mocks base method.
func (m *MockDisk) Free(ctx context.Context, path string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Free", ctx, path)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Free indicates an expected call of Free.
func (mr *MockDiskMockRecorder) Free(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Free", reflect.TypeOf((*MockDisk)(nil).Free), ctx, path)
}
