// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=supervisor/mock_services.go -package=supervisor -mock_names=Services=MockServices
//

// Package supervisor is a generated GoMock package.
package supervisor

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockServices is a mock of Services interface.
type MockServices struct {
	ctrl     *gomock.Controller
	recorder *MockServicesMockRecorder
	isgomock struct{}
}

// MockServicesMockRecorder is the mock recorder for MockServices.
type MockServicesMockRecorder struct {
	mock *MockServices
}

// NewMockServices creates a new mock instance.
func NewMockServices(ctrl *gomock.Controller) *MockServices {
	mock := &MockServices{ctrl: ctrl}
	mock.recorder = &MockServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServices) EXPECT() *MockServicesMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockServices) List(ctx context.Context, executionID string) ([]entity.ServiceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, executionID)
	ret0, _ := ret[0].([]entity.ServiceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServicesMockRecorder) List(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServices)(nil).List), ctx, executionID)
}

// Logs mocks base method.
func (m *MockServices) Logs(ctx context.Context, executionID, name string, tail int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs", ctx, executionID, name, tail)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logs indicates an expected call of Logs.
func (mr *MockServicesMockRecorder) Logs(ctx, executionID, name, tail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockServices)(nil).Logs), ctx, executionID, name, tail)
}

// Release mocks base method.
func (m *MockServices) Release(ctx context.Context, executionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, executionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockServicesMockRecorder) Release(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockServices)(nil).Release), ctx, executionID)
}

// Restart mocks base method.
func (m *MockServices) Restart(ctx context.Context, executionID, name string) (entity.ServiceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart", ctx, executionID, name)
	ret0, _ := ret[0].(entity.ServiceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restart indicates an expected call of Restart.
func (mr *MockServicesMockRecorder) Restart(ctx, executionID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockServices)(nil).Restart), ctx, executionID, name)
}

// Run mocks base method.
func (m *MockServices) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockServicesMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockServices)(nil).Run), ctx)
}

// Start mocks base method.
func (m *MockServices) Start(ctx context.Context, executionID string, wanted entity.Service) (entity.ServiceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, executionID, wanted)
	ret0, _ := ret[0].(entity.ServiceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockServicesMockRecorder) Start(ctx, executionID, wanted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockServices)(nil).Start), ctx, executionID, wanted)
}

// Step mocks base method.
func (m *MockServices) Step(ctx context.Context, executionID string, step entity.Step) (entity.StepResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Step", ctx, executionID, step)
	ret0, _ := ret[0].(entity.StepResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Step indicates an expected call of Step.
func (mr *MockServicesMockRecorder) Step(ctx, executionID, step any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Step", reflect.TypeOf((*MockServices)(nil).Step), ctx, executionID, step)
}

// Stop mocks base method.
func (m *MockServices) Stop(ctx context.Context, executionID, name string) (entity.ServiceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, executionID, name)
	ret0, _ := ret[0].(entity.ServiceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stop indicates an expected call of Stop.
func (mr *MockServicesMockRecorder) Stop(ctx, executionID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockServices)(nil).Stop), ctx, executionID, name)
}
