// Code generated by MockGen. DO NOT EDIT.
// Source: inventory.go
//
// Generated by this command:
//
//	mockgen -source=inventory.go -destination=inventory/mock_inventory.go -package=inventory -mock_names=Inventory=MockInventory
//

// Package inventory is a generated GoMock package.
package inventory

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockInventory is a mock of Inventory interface.
type MockInventory struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryMockRecorder
	isgomock struct{}
}

// MockInventoryMockRecorder is the mock recorder for MockInventory.
type MockInventoryMockRecorder struct {
	mock *MockInventory
}

// NewMockInventory creates a new mock instance.
func NewMockInventory(ctrl *gomock.Controller) *MockInventory {
	mock := &MockInventory{ctrl: ctrl}
	mock.recorder = &MockInventoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventory) EXPECT() *MockInventoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockInventory) List(ctx context.Context) ([]entity.Codebase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Codebase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInventoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInventory)(nil).List), ctx)
}

// Load mocks base method.
func (m *MockInventory) Load(ctx context.Context, root string) (entity.Codebase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, root)
	ret0, _ := ret[0].(entity.Codebase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockInventoryMockRecorder) Load(ctx, root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockInventory)(nil).Load), ctx, root)
}

// Remove mocks base method.
func (m *MockInventory) Remove(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockInventoryMockRecorder) Remove(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockInventory)(nil).Remove), ctx, id)
}

// Save mocks base method.
func (m *MockInventory) Save(ctx context.Context, codebase entity.Codebase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, codebase)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockInventoryMockRecorder) Save(ctx, codebase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockInventory)(nil).Save), ctx, codebase)
}
