// Code generated by MockGen. DO NOT EDIT.
// Source: sandbox.go
//
// Generated by this command:
//
//	mockgen -source=sandbox.go -destination=sandbox/mock_sandbox.go -package=sandbox -mock_names=Sandbox=MockSandbox
//

// Package sandbox is a generated GoMock package.
package sandbox

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/usenorn/runner/internal/entity"
	repository "github.com/usenorn/runner/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockSandbox is a mock of Sandbox interface.
type MockSandbox struct {
	ctrl     *gomock.Controller
	recorder *MockSandboxMockRecorder
	isgomock struct{}
}

// MockSandboxMockRecorder is the mock recorder for MockSandbox.
type MockSandboxMockRecorder struct {
	mock *MockSandbox
}

// NewMockSandbox creates a new mock instance.
func NewMockSandbox(ctrl *gomock.Controller) *MockSandbox {
	mock := &MockSandbox{ctrl: ctrl}
	mock.recorder = &MockSandboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSandbox) EXPECT() *MockSandboxMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockSandbox) Check(ctx context.Context, runtime entity.Runtime) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, runtime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockSandboxMockRecorder) Check(ctx, runtime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockSandbox)(nil).Check), ctx, runtime)
}

// Close mocks base method.
func (m *MockSandbox) Close(ctx context.Context, box entity.Sandbox) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, box)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSandboxMockRecorder) Close(ctx, box any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSandbox)(nil).Close), ctx, box)
}

// Has mocks base method.
func (m *MockSandbox) Has(ctx context.Context, box entity.Sandbox, command string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", ctx, box, command)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Has indicates an expected call of Has.
func (mr *MockSandboxMockRecorder) Has(ctx, box, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockSandbox)(nil).Has), ctx, box, command)
}

// Open mocks base method.
func (m *MockSandbox) Open(ctx context.Context, spec entity.SandboxSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockSandboxMockRecorder) Open(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockSandbox)(nil).Open), ctx, spec)
}

// Run mocks base method.
func (m *MockSandbox) Run(ctx context.Context, box entity.Sandbox, launch repository.Launch, timeout time.Duration) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, box, launch, timeout)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockSandboxMockRecorder) Run(ctx, box, launch, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockSandbox)(nil).Run), ctx, box, launch, timeout)
}

// Start mocks base method.
func (m *MockSandbox) Start(ctx context.Context, box entity.Sandbox, launch repository.Launch) (repository.Child, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, box, launch)
	ret0, _ := ret[0].(repository.Child)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockSandboxMockRecorder) Start(ctx, box, launch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSandbox)(nil).Start), ctx, box, launch)
}

// Sweep mocks base method.
func (m *MockSandbox) Sweep(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sweep", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sweep indicates an expected call of Sweep.
func (mr *MockSandboxMockRecorder) Sweep(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sweep", reflect.TypeOf((*MockSandbox)(nil).Sweep), ctx)
}

// Tools mocks base method.
func (m *MockSandbox) Tools(box entity.Sandbox) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tools", box)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tools indicates an expected call of Tools.
func (mr *MockSandboxMockRecorder) Tools(box any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tools", reflect.TypeOf((*MockSandbox)(nil).Tools), box)
}
