// Code generated by MockGen. DO NOT EDIT.
// Source: forge.go
//
// Generated by this command:
//
//	mockgen -source=forge.go -destination=forge/mock_forge.go -package=forge -mock_names=Forge=MockForge
//

// Package forge is a generated GoMock package.
package forge

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockForge is a mock of Forge interface.
type MockForge struct {
	ctrl     *gomock.Controller
	recorder *MockForgeMockRecorder
	isgomock struct{}
}

// MockForgeMockRecorder is the mock recorder for MockForge.
type MockForgeMockRecorder struct {
	mock *MockForge
}

// NewMockForge creates a new mock instance.
func NewMockForge(ctrl *gomock.Controller) *MockForge {
	mock := &MockForge{ctrl: ctrl}
	mock.recorder = &MockForgeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForge) EXPECT() *MockForgeMockRecorder {
	return m.recorder
}

// Available mocks base method.
func (m *MockForge) Available(ctx context.Context, dir string) (entity.ForgeKind, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Available", ctx, dir)
	ret0, _ := ret[0].(entity.ForgeKind)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Available indicates an expected call of Available.
func (mr *MockForgeMockRecorder) Available(ctx, dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Available", reflect.TypeOf((*MockForge)(nil).Available), ctx, dir)
}

// Existing mocks base method.
func (m *MockForge) Existing(ctx context.Context, dir, branch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Existing", ctx, dir, branch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Existing indicates an expected call of Existing.
func (mr *MockForgeMockRecorder) Existing(ctx, dir, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Existing", reflect.TypeOf((*MockForge)(nil).Existing), ctx, dir, branch)
}

// Open mocks base method.
func (m *MockForge) Open(ctx context.Context, dir string, request entity.PullRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, dir, request)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockForgeMockRecorder) Open(ctx, dir, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockForge)(nil).Open), ctx, dir, request)
}
