// Code generated by MockGen. DO NOT EDIT.
// Source: sessions.go
//
// Generated by this command:
//
//	mockgen -source=sessions.go -destination=session/mock_sessions.go -package=session -mock_names=Sessions=MockSessions
//

// Package session is a generated GoMock package.
package session

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSessions is a mock of Sessions interface.
type MockSessions struct {
	ctrl     *gomock.Controller
	recorder *MockSessionsMockRecorder
	isgomock struct{}
}

// MockSessionsMockRecorder is the mock recorder for MockSessions.
type MockSessionsMockRecorder struct {
	mock *MockSessions
}

// NewMockSessions creates a new mock instance.
func NewMockSessions(ctrl *gomock.Controller) *MockSessions {
	mock := &MockSessions{ctrl: ctrl}
	mock.recorder = &MockSessionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessions) EXPECT() *MockSessionsMockRecorder {
	return m.recorder
}

// Access mocks base method.
func (m *MockSessions) Access(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Access", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Access indicates an expected call of Access.
func (mr *MockSessionsMockRecorder) Access(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Access", reflect.TypeOf((*MockSessions)(nil).Access), ctx)
}

// Adopt mocks base method.
func (m *MockSessions) Adopt(ctx context.Context, identity entity.Identity) entity.SessionReport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Adopt", ctx, identity)
	ret0, _ := ret[0].(entity.SessionReport)
	return ret0
}

// Adopt indicates an expected call of Adopt.
func (mr *MockSessionsMockRecorder) Adopt(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Adopt", reflect.TypeOf((*MockSessions)(nil).Adopt), ctx, identity)
}

// Forget mocks base method.
func (m *MockSessions) Forget() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Forget")
}

// Forget indicates an expected call of Forget.
func (mr *MockSessionsMockRecorder) Forget() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Forget", reflect.TypeOf((*MockSessions)(nil).Forget))
}

// Report mocks base method.
func (m *MockSessions) Report() entity.SessionReport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report")
	ret0, _ := ret[0].(entity.SessionReport)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MockSessionsMockRecorder) Report() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockSessions)(nil).Report))
}

// Run mocks base method.
func (m *MockSessions) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockSessionsMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockSessions)(nil).Run), ctx)
}
