// Code generated by MockGen. DO NOT EDIT.
// Source: changesets.go
//
// Generated by this command:
//
//	mockgen -source=changesets.go -destination=changeset/mock_changesets.go -package=changeset -mock_names=ChangeSets=MockChangeSets
//

// Package changeset is a generated GoMock package.
package changeset

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockChangeSets is a mock of ChangeSets interface.
type MockChangeSets struct {
	ctrl     *gomock.Controller
	recorder *MockChangeSetsMockRecorder
	isgomock struct{}
}

// MockChangeSetsMockRecorder is the mock recorder for MockChangeSets.
type MockChangeSetsMockRecorder struct {
	mock *MockChangeSets
}

// NewMockChangeSets creates a new mock instance.
func NewMockChangeSets(ctrl *gomock.Controller) *MockChangeSets {
	mock := &MockChangeSets{ctrl: ctrl}
	mock.recorder = &MockChangeSetsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangeSets) EXPECT() *MockChangeSetsMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockChangeSets) Publish(ctx context.Context, execution entity.Execution, snapshot entity.Snapshot, completion entity.Completion, previews []entity.PreviewLink) (entity.ChangeSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, execution, snapshot, completion, previews)
	ret0, _ := ret[0].(entity.ChangeSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockChangeSetsMockRecorder) Publish(ctx, execution, snapshot, completion, previews any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockChangeSets)(nil).Publish), ctx, execution, snapshot, completion, previews)
}

// Uncommitted mocks base method.
func (m *MockChangeSets) Uncommitted(ctx context.Context, snapshot entity.Snapshot) ([]entity.UncommittedWork, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uncommitted", ctx, snapshot)
	ret0, _ := ret[0].([]entity.UncommittedWork)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Uncommitted indicates an expected call of Uncommitted.
func (mr *MockChangeSetsMockRecorder) Uncommitted(ctx, snapshot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uncommitted", reflect.TypeOf((*MockChangeSets)(nil).Uncommitted), ctx, snapshot)
}
