// Code generated by MockGen. DO NOT EDIT.
// Source: servicelog.go
//
// Generated by this command:
//
//	mockgen -source=servicelog.go -destination=servicelog/mock_servicelog.go -package=servicelog -mock_names=ServiceLog=MockServiceLog
//

// Package servicelog is a generated GoMock package.
package servicelog

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceLog is a mock of ServiceLog interface.
type MockServiceLog struct {
	ctrl     *gomock.Controller
	recorder *MockServiceLogMockRecorder
	isgomock struct{}
}

// MockServiceLogMockRecorder is the mock recorder for MockServiceLog.
type MockServiceLogMockRecorder struct {
	mock *MockServiceLog
}

// NewMockServiceLog creates a new mock instance.
func NewMockServiceLog(ctrl *gomock.Controller) *MockServiceLog {
	mock := &MockServiceLog{ctrl: ctrl}
	mock.recorder = &MockServiceLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceLog) EXPECT() *MockServiceLogMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockServiceLog) Open(ctx context.Context, run, name string) (io.WriteCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, run, name)
	ret0, _ := ret[0].(io.WriteCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockServiceLogMockRecorder) Open(ctx, run, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockServiceLog)(nil).Open), ctx, run, name)
}

// Tail mocks base method.
func (m *MockServiceLog) Tail(ctx context.Context, run, name string, lines int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tail", ctx, run, name, lines)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tail indicates an expected call of Tail.
func (mr *MockServiceLogMockRecorder) Tail(ctx, run, name, lines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tail", reflect.TypeOf((*MockServiceLog)(nil).Tail), ctx, run, name, lines)
}
