// Code generated by MockGen. DO NOT EDIT.
// Source: toolkit.go
//
// Generated by this command:
//
//	mockgen -source=toolkit.go -destination=toolkit/mock_toolkit.go -package=toolkit -mock_names=Toolkit=MockToolkit
//

// Package toolkit is a generated GoMock package.
package toolkit

import (
	context "context"
	http "net/http"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockToolkit is a mock of Toolkit interface.
type MockToolkit struct {
	ctrl     *gomock.Controller
	recorder *MockToolkitMockRecorder
	isgomock struct{}
}

// MockToolkitMockRecorder is the mock recorder for MockToolkit.
type MockToolkitMockRecorder struct {
	mock *MockToolkit
}

// NewMockToolkit creates a new mock instance.
func NewMockToolkit(ctrl *gomock.Controller) *MockToolkit {
	mock := &MockToolkit{ctrl: ctrl}
	mock.recorder = &MockToolkitMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolkit) EXPECT() *MockToolkitMockRecorder {
	return m.recorder
}

// InstallSkill mocks base method.
func (m *MockToolkit) InstallSkill(ctx context.Context, skill entity.ToolkitSkill, plugin string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallSkill", ctx, skill, plugin)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstallSkill indicates an expected call of InstallSkill.
func (mr *MockToolkitMockRecorder) InstallSkill(ctx, skill, plugin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallSkill", reflect.TypeOf((*MockToolkit)(nil).InstallSkill), ctx, skill, plugin)
}

// NornHandler mocks base method.
func (m *MockToolkit) NornHandler(accessToken string) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NornHandler", accessToken)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// NornHandler indicates an expected call of NornHandler.
func (mr *MockToolkitMockRecorder) NornHandler(accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NornHandler", reflect.TypeOf((*MockToolkit)(nil).NornHandler), accessToken)
}

// ReachNorn mocks base method.
func (m *MockToolkit) ReachNorn(ctx context.Context, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReachNorn", ctx, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReachNorn indicates an expected call of ReachNorn.
func (mr *MockToolkitMockRecorder) ReachNorn(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReachNorn", reflect.TypeOf((*MockToolkit)(nil).ReachNorn), ctx, accessToken)
}
