// Code generated by MockGen. DO NOT EDIT.
// Source: codebases.go
//
// Generated by this command:
//
//	mockgen -source=codebases.go -destination=codebase/mock_codebases.go -package=codebase -mock_names=Codebases=MockCodebases
//

// Package codebase is a generated GoMock package.
package codebase

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	service "github.com/usenorn/runner/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockCodebases is a mock of Codebases interface.
type MockCodebases struct {
	ctrl     *gomock.Controller
	recorder *MockCodebasesMockRecorder
	isgomock struct{}
}

// MockCodebasesMockRecorder is the mock recorder for MockCodebases.
type MockCodebasesMockRecorder struct {
	mock *MockCodebases
}

// NewMockCodebases creates a new mock instance.
func NewMockCodebases(ctrl *gomock.Controller) *MockCodebases {
	mock := &MockCodebases{ctrl: ctrl}
	mock.recorder = &MockCodebasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodebases) EXPECT() *MockCodebasesMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockCodebases) Accept(ctx context.Context, scan service.Scan) (entity.Codebase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", ctx, scan)
	ret0, _ := ret[0].(entity.Codebase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accept indicates an expected call of Accept.
func (mr *MockCodebasesMockRecorder) Accept(ctx, scan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockCodebases)(nil).Accept), ctx, scan)
}

// List mocks base method.
func (m *MockCodebases) List(ctx context.Context) ([]entity.Codebase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Codebase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCodebasesMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCodebases)(nil).List), ctx)
}

// Run mocks base method.
func (m *MockCodebases) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockCodebasesMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCodebases)(nil).Run), ctx)
}

// Scan mocks base method.
func (m *MockCodebases) Scan(ctx context.Context, root string) (service.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", ctx, root)
	ret0, _ := ret[0].(service.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockCodebasesMockRecorder) Scan(ctx, root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockCodebases)(nil).Scan), ctx, root)
}
