// Code generated by MockGen. DO NOT EDIT.
// Source: toolchains.go
//
// Generated by this command:
//
//	mockgen -source=toolchains.go -destination=toolchain/mock_toolchains.go -package=toolchain -mock_names=Toolchains=MockToolchains
//

// Package toolchain is a generated GoMock package.
package toolchain

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockToolchains is a mock of Toolchains interface.
type MockToolchains struct {
	ctrl     *gomock.Controller
	recorder *MockToolchainsMockRecorder
	isgomock struct{}
}

// MockToolchainsMockRecorder is the mock recorder for MockToolchains.
type MockToolchainsMockRecorder struct {
	mock *MockToolchains
}

// NewMockToolchains creates a new mock instance.
func NewMockToolchains(ctrl *gomock.Controller) *MockToolchains {
	mock := &MockToolchains{ctrl: ctrl}
	mock.recorder = &MockToolchainsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolchains) EXPECT() *MockToolchainsMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockToolchains) Check(ctx context.Context, probe entity.ToolchainProbe) (entity.ToolchainReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, probe)
	ret0, _ := ret[0].(entity.ToolchainReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockToolchainsMockRecorder) Check(ctx, probe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockToolchains)(nil).Check), ctx, probe)
}

// Doctor mocks base method.
func (m *MockToolchains) Doctor(ctx context.Context) (entity.Doctor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Doctor", ctx)
	ret0, _ := ret[0].(entity.Doctor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Doctor indicates an expected call of Doctor.
func (mr *MockToolchainsMockRecorder) Doctor(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Doctor", reflect.TypeOf((*MockToolchains)(nil).Doctor), ctx)
}
