// Code generated by MockGen. DO NOT EDIT.
// Source: previews.go
//
// Generated by this command:
//
//	mockgen -source=previews.go -destination=preview/mock_previews.go -package=preview -mock_names=Previews=MockPreviews
//

// Package preview is a generated GoMock package.
package preview

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPreviews is a mock of Previews interface.
type MockPreviews struct {
	ctrl     *gomock.Controller
	recorder *MockPreviewsMockRecorder
	isgomock struct{}
}

// MockPreviewsMockRecorder is the mock recorder for MockPreviews.
type MockPreviewsMockRecorder struct {
	mock *MockPreviews
}

// NewMockPreviews creates a new mock instance.
func NewMockPreviews(ctrl *gomock.Controller) *MockPreviews {
	mock := &MockPreviews{ctrl: ctrl}
	mock.recorder = &MockPreviewsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreviews) EXPECT() *MockPreviewsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPreviews) Close(ctx context.Context, executionID, name string) (entity.Preview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, executionID, name)
	ret0, _ := ret[0].(entity.Preview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Close indicates an expected call of Close.
func (mr *MockPreviewsMockRecorder) Close(ctx, executionID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPreviews)(nil).Close), ctx, executionID, name)
}

// Expose mocks base method.
func (m *MockPreviews) Expose(ctx context.Context, executionID string, wanted entity.Preview) (entity.Preview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expose", ctx, executionID, wanted)
	ret0, _ := ret[0].(entity.Preview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Expose indicates an expected call of Expose.
func (mr *MockPreviewsMockRecorder) Expose(ctx, executionID, wanted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expose", reflect.TypeOf((*MockPreviews)(nil).Expose), ctx, executionID, wanted)
}

// List mocks base method.
func (m *MockPreviews) List(ctx context.Context, executionID string) ([]entity.Preview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, executionID)
	ret0, _ := ret[0].([]entity.Preview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPreviewsMockRecorder) List(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPreviews)(nil).List), ctx, executionID)
}

// Release mocks base method.
func (m *MockPreviews) Release(ctx context.Context, executionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release", ctx, executionID)
}

// Release indicates an expected call of Release.
func (mr *MockPreviewsMockRecorder) Release(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockPreviews)(nil).Release), ctx, executionID)
}
