// Code generated by MockGen. DO NOT EDIT.
// Source: questions.go
//
// Generated by this command:
//
//	mockgen -source=questions.go -destination=question/mock_questions.go -package=question -mock_names=Questions=MockQuestions
//

// Package question is a generated GoMock package.
package question

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockQuestions is a mock of Questions interface.
type MockQuestions struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionsMockRecorder
	isgomock struct{}
}

// MockQuestionsMockRecorder is the mock recorder for MockQuestions.
type MockQuestionsMockRecorder struct {
	mock *MockQuestions
}

// NewMockQuestions creates a new mock instance.
func NewMockQuestions(ctrl *gomock.Controller) *MockQuestions {
	mock := &MockQuestions{ctrl: ctrl}
	mock.recorder = &MockQuestionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestions) EXPECT() *MockQuestionsMockRecorder {
	return m.recorder
}

// Answered mocks base method.
func (m *MockQuestions) Answered(ctx context.Context, executionID string, answer entity.Answer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Answered", ctx, executionID, answer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Answered indicates an expected call of Answered.
func (mr *MockQuestionsMockRecorder) Answered(ctx, executionID, answer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Answered", reflect.TypeOf((*MockQuestions)(nil).Answered), ctx, executionID, answer)
}

// Ask mocks base method.
func (m *MockQuestions) Ask(ctx context.Context, executionID string, question entity.Question) (entity.Asked, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ask", ctx, executionID, question)
	ret0, _ := ret[0].(entity.Asked)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ask indicates an expected call of Ask.
func (mr *MockQuestionsMockRecorder) Ask(ctx, executionID, question any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ask", reflect.TypeOf((*MockQuestions)(nil).Ask), ctx, executionID, question)
}

// Forget mocks base method.
func (m *MockQuestions) Forget(ctx context.Context, executionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Forget", ctx, executionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Forget indicates an expected call of Forget.
func (mr *MockQuestionsMockRecorder) Forget(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Forget", reflect.TypeOf((*MockQuestions)(nil).Forget), ctx, executionID)
}

// Restore mocks base method.
func (m *MockQuestions) Restore(ctx context.Context, executionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, executionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockQuestionsMockRecorder) Restore(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockQuestions)(nil).Restore), ctx, executionID)
}

// Take mocks base method.
func (m *MockQuestions) Take(ctx context.Context, executionID string) (entity.Question, entity.Answer, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Take", ctx, executionID)
	ret0, _ := ret[0].(entity.Question)
	ret1, _ := ret[1].(entity.Answer)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Take indicates an expected call of Take.
func (mr *MockQuestionsMockRecorder) Take(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Take", reflect.TypeOf((*MockQuestions)(nil).Take), ctx, executionID)
}

// Waiting mocks base method.
func (m *MockQuestions) Waiting(executionID string) (entity.Question, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Waiting", executionID)
	ret0, _ := ret[0].(entity.Question)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Waiting indicates an expected call of Waiting.
func (mr *MockQuestionsMockRecorder) Waiting(executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Waiting", reflect.TypeOf((*MockQuestions)(nil).Waiting), executionID)
}
