// Code generated by MockGen. DO NOT EDIT.
// Source: toolchain.go
//
// Generated by this command:
//
//	mockgen -source=toolchain.go -destination=toolchain/mock_toolchain.go -package=toolchain -mock_names=Toolchain=MockToolchain
//

// Package toolchain is a generated GoMock package.
package toolchain

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockToolchain is a mock of Toolchain interface.
type MockToolchain struct {
	ctrl     *gomock.Controller
	recorder *MockToolchainMockRecorder
	isgomock struct{}
}

// MockToolchainMockRecorder is the mock recorder for MockToolchain.
type MockToolchainMockRecorder struct {
	mock *MockToolchain
}

// NewMockToolchain creates a new mock instance.
func NewMockToolchain(ctrl *gomock.Controller) *MockToolchain {
	mock := &MockToolchain{ctrl: ctrl}
	mock.recorder = &MockToolchainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolchain) EXPECT() *MockToolchainMockRecorder {
	return m.recorder
}

// Locate mocks base method.
func (m *MockToolchain) Locate(name string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Locate", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Locate indicates an expected call of Locate.
func (mr *MockToolchainMockRecorder) Locate(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locate", reflect.TypeOf((*MockToolchain)(nil).Locate), name)
}

// Manifests mocks base method.
func (m *MockToolchain) Manifests(ctx context.Context, roots []entity.ManifestRoot) ([]entity.Manifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Manifests", ctx, roots)
	ret0, _ := ret[0].([]entity.Manifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Manifests indicates an expected call of Manifests.
func (mr *MockToolchainMockRecorder) Manifests(ctx, roots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Manifests", reflect.TypeOf((*MockToolchain)(nil).Manifests), ctx, roots)
}
