// Code generated by MockGen. DO NOT EDIT.
// Source: worktree.go
//
// Generated by this command:
//
//	mockgen -source=worktree.go -destination=worktree/mock_worktree.go -package=worktree -mock_names=Worktree=MockWorktree
//

// Package worktree is a generated GoMock package.
package worktree

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockWorktree is a mock of Worktree interface.
type MockWorktree struct {
	ctrl     *gomock.Controller
	recorder *MockWorktreeMockRecorder
	isgomock struct{}
}

// MockWorktreeMockRecorder is the mock recorder for MockWorktree.
type MockWorktreeMockRecorder struct {
	mock *MockWorktree
}

// NewMockWorktree creates a new mock instance.
func NewMockWorktree(ctrl *gomock.Controller) *MockWorktree {
	mock := &MockWorktree{ctrl: ctrl}
	mock.recorder = &MockWorktreeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorktree) EXPECT() *MockWorktreeMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockWorktree) Add(ctx context.Context, repository, dest, sha string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, repository, dest, sha)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockWorktreeMockRecorder) Add(ctx, repository, dest, sha any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockWorktree)(nil).Add), ctx, repository, dest, sha)
}

// Apply mocks base method.
func (m *MockWorktree) Apply(ctx context.Context, dest string, patch []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, dest, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockWorktreeMockRecorder) Apply(ctx, dest, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockWorktree)(nil).Apply), ctx, dest, patch)
}

// Branch mocks base method.
func (m *MockWorktree) Branch(ctx context.Context, dest, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Branch", ctx, dest, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Branch indicates an expected call of Branch.
func (mr *MockWorktreeMockRecorder) Branch(ctx, dest, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Branch", reflect.TypeOf((*MockWorktree)(nil).Branch), ctx, dest, name)
}

// Changed mocks base method.
func (m *MockWorktree) Changed(ctx context.Context, repository string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Changed", ctx, repository)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Changed indicates an expected call of Changed.
func (mr *MockWorktreeMockRecorder) Changed(ctx, repository any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Changed", reflect.TypeOf((*MockWorktree)(nil).Changed), ctx, repository)
}

// Clone mocks base method.
func (m *MockWorktree) Clone(ctx context.Context, repository, dest, sha string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", ctx, repository, dest, sha)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockWorktreeMockRecorder) Clone(ctx, repository, dest, sha any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockWorktree)(nil).Clone), ctx, repository, dest, sha)
}

// Commit mocks base method.
func (m *MockWorktree) Commit(ctx context.Context, dest, message string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx, dest, message)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commit indicates an expected call of Commit.
func (mr *MockWorktreeMockRecorder) Commit(ctx, dest, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockWorktree)(nil).Commit), ctx, dest, message)
}

// Commits mocks base method.
func (m *MockWorktree) Commits(ctx context.Context, dest, base string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commits", ctx, dest, base)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commits indicates an expected call of Commits.
func (mr *MockWorktreeMockRecorder) Commits(ctx, dest, base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commits", reflect.TypeOf((*MockWorktree)(nil).Commits), ctx, dest, base)
}

// Diff mocks base method.
func (m *MockWorktree) Diff(ctx context.Context, repository string, paths []string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Diff", ctx, repository, paths)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Diff indicates an expected call of Diff.
func (mr *MockWorktreeMockRecorder) Diff(ctx, repository, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Diff", reflect.TypeOf((*MockWorktree)(nil).Diff), ctx, repository, paths)
}

// Diffstat mocks base method.
func (m *MockWorktree) Diffstat(ctx context.Context, dest, base string) (entity.Diffstat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Diffstat", ctx, dest, base)
	ret0, _ := ret[0].(entity.Diffstat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Diffstat indicates an expected call of Diffstat.
func (mr *MockWorktreeMockRecorder) Diffstat(ctx, dest, base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Diffstat", reflect.TypeOf((*MockWorktree)(nil).Diffstat), ctx, dest, base)
}

// Fetch mocks base method.
func (m *MockWorktree) Fetch(ctx context.Context, repository, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, repository, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fetch indicates an expected call of Fetch.
func (mr *MockWorktreeMockRecorder) Fetch(ctx, repository, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockWorktree)(nil).Fetch), ctx, repository, branch)
}

// Head mocks base method.
func (m *MockWorktree) Head(ctx context.Context, repository string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Head", ctx, repository)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Head indicates an expected call of Head.
func (mr *MockWorktreeMockRecorder) Head(ctx, repository any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Head", reflect.TypeOf((*MockWorktree)(nil).Head), ctx, repository)
}

// Patch mocks base method.
func (m *MockWorktree) Patch(ctx context.Context, dest, base string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ctx, dest, base)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockWorktreeMockRecorder) Patch(ctx, dest, base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockWorktree)(nil).Patch), ctx, dest, base)
}

// Prune mocks base method.
func (m *MockWorktree) Prune(ctx context.Context, repository string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", ctx, repository)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prune indicates an expected call of Prune.
func (mr *MockWorktreeMockRecorder) Prune(ctx, repository any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockWorktree)(nil).Prune), ctx, repository)
}

// Push mocks base method.
func (m *MockWorktree) Push(ctx context.Context, dest, url, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", ctx, dest, url, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockWorktreeMockRecorder) Push(ctx, dest, url, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockWorktree)(nil).Push), ctx, dest, url, branch)
}

// Remote mocks base method.
func (m *MockWorktree) Remote(ctx context.Context, repository string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remote", ctx, repository)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Remote indicates an expected call of Remote.
func (mr *MockWorktreeMockRecorder) Remote(ctx, repository any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remote", reflect.TypeOf((*MockWorktree)(nil).Remote), ctx, repository)
}

// Remove mocks base method.
func (m *MockWorktree) Remove(ctx context.Context, repository, dest string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, repository, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWorktreeMockRecorder) Remove(ctx, repository, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWorktree)(nil).Remove), ctx, repository, dest)
}

// Resolve mocks base method.
func (m *MockWorktree) Resolve(ctx context.Context, repository string, revisions ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, repository}
	for _, a := range revisions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Resolve", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockWorktreeMockRecorder) Resolve(ctx, repository any, revisions ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, repository}, revisions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockWorktree)(nil).Resolve), varargs...)
}

// Stage mocks base method.
func (m *MockWorktree) Stage(ctx context.Context, dest string, paths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stage", ctx, dest, paths)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stage indicates an expected call of Stage.
func (mr *MockWorktreeMockRecorder) Stage(ctx, dest, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stage", reflect.TypeOf((*MockWorktree)(nil).Stage), ctx, dest, paths)
}

// Submodules mocks base method.
func (m *MockWorktree) Submodules(ctx context.Context, dest string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submodules", ctx, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Submodules indicates an expected call of Submodules.
func (mr *MockWorktreeMockRecorder) Submodules(ctx, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submodules", reflect.TypeOf((*MockWorktree)(nil).Submodules), ctx, dest)
}

// Untracked mocks base method.
func (m *MockWorktree) Untracked(ctx context.Context, repository string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Untracked", ctx, repository)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Untracked indicates an expected call of Untracked.
func (mr *MockWorktreeMockRecorder) Untracked(ctx, repository any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Untracked", reflect.TypeOf((*MockWorktree)(nil).Untracked), ctx, repository)
}
