// Code generated by MockGen. DO NOT EDIT.
// Source: settings.go
//
// Generated by this command:
//
//	mockgen -source=settings.go -destination=settings/mock_settings.go -package=settings -mock_names=Settings=MockSettings
//

// Package settings is a generated GoMock package.
package settings

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	repository "github.com/usenorn/runner/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockSettings is a mock of Settings interface.
type MockSettings struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsMockRecorder
	isgomock struct{}
}

// MockSettingsMockRecorder is the mock recorder for MockSettings.
type MockSettingsMockRecorder struct {
	mock *MockSettings
}

// NewMockSettings creates a new mock instance.
func NewMockSettings(ctrl *gomock.Controller) *MockSettings {
	mock := &MockSettings{ctrl: ctrl}
	mock.recorder = &MockSettingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettings) EXPECT() *MockSettingsMockRecorder {
	return m.recorder
}

// Ignores mocks base method.
func (m *MockSettings) Ignores(ctx context.Context, dir string) ([]entity.IgnoreRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ignores", ctx, dir)
	ret0, _ := ret[0].([]entity.IgnoreRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ignores indicates an expected call of Ignores.
func (mr *MockSettingsMockRecorder) Ignores(ctx, dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ignores", reflect.TypeOf((*MockSettings)(nil).Ignores), ctx, dir)
}

// Load mocks base method.
func (m *MockSettings) Load(ctx context.Context, root string) (repository.CodebaseSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, root)
	ret0, _ := ret[0].(repository.CodebaseSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockSettingsMockRecorder) Load(ctx, root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockSettings)(nil).Load), ctx, root)
}

// Plan mocks base method.
func (m *MockSettings) Plan(ctx context.Context, root string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Plan", ctx, root)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Plan indicates an expected call of Plan.
func (mr *MockSettingsMockRecorder) Plan(ctx, root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Plan", reflect.TypeOf((*MockSettings)(nil).Plan), ctx, root)
}
