// Code generated by MockGen. DO NOT EDIT.
// Source: materialiser.go
//
// Generated by this command:
//
//	mockgen -source=materialiser.go -destination=materialiser/mock_materialiser.go -package=materialiser -mock_names=Materialiser=MockMaterialiser
//

// Package materialiser is a generated GoMock package.
package materialiser

import (
	context "context"
	reflect "reflect"

	repository "github.com/usenorn/runner/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockMaterialiser is a mock of Materialiser interface.
type MockMaterialiser struct {
	ctrl     *gomock.Controller
	recorder *MockMaterialiserMockRecorder
	isgomock struct{}
}

// MockMaterialiserMockRecorder is the mock recorder for MockMaterialiser.
type MockMaterialiserMockRecorder struct {
	mock *MockMaterialiser
}

// NewMockMaterialiser creates a new mock instance.
func NewMockMaterialiser(ctrl *gomock.Controller) *MockMaterialiser {
	mock := &MockMaterialiser{ctrl: ctrl}
	mock.recorder = &MockMaterialiserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaterialiser) EXPECT() *MockMaterialiserMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockMaterialiser) Copy(ctx context.Context, from, to string, skip repository.SkipFunc, budget int64) (repository.Materialised, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", ctx, from, to, skip, budget)
	ret0, _ := ret[0].(repository.Materialised)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Copy indicates an expected call of Copy.
func (mr *MockMaterialiserMockRecorder) Copy(ctx, from, to, skip, budget any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockMaterialiser)(nil).Copy), ctx, from, to, skip, budget)
}

// CopyPaths mocks base method.
func (m *MockMaterialiser) CopyPaths(ctx context.Context, from, to string, relPaths []string) (repository.Materialised, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyPaths", ctx, from, to, relPaths)
	ret0, _ := ret[0].(repository.Materialised)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyPaths indicates an expected call of CopyPaths.
func (mr *MockMaterialiserMockRecorder) CopyPaths(ctx, from, to, relPaths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyPaths", reflect.TypeOf((*MockMaterialiser)(nil).CopyPaths), ctx, from, to, relPaths)
}

// Remove mocks base method.
func (m *MockMaterialiser) Remove(ctx context.Context, dir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockMaterialiserMockRecorder) Remove(ctx, dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockMaterialiser)(nil).Remove), ctx, dir)
}
