// Code generated by MockGen. DO NOT EDIT.
// Source: runtoken.go
//
// Generated by this command:
//
//	mockgen -source=runtoken.go -destination=runtoken/mock_runtoken.go -package=runtoken -mock_names=RunToken=MockRunToken
//

// Package runtoken is a generated GoMock package.
package runtoken

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRunToken is a mock of RunToken interface.
type MockRunToken struct {
	ctrl     *gomock.Controller
	recorder *MockRunTokenMockRecorder
	isgomock struct{}
}

// MockRunTokenMockRecorder is the mock recorder for MockRunToken.
type MockRunTokenMockRecorder struct {
	mock *MockRunToken
}

// NewMockRunToken creates a new mock instance.
func NewMockRunToken(ctrl *gomock.Controller) *MockRunToken {
	mock := &MockRunToken{ctrl: ctrl}
	mock.recorder = &MockRunTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunToken) EXPECT() *MockRunTokenMockRecorder {
	return m.recorder
}

// Allows mocks base method.
func (m *MockRunToken) Allows(ctx context.Context, run, token string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allows", ctx, run, token)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Allows indicates an expected call of Allows.
func (mr *MockRunTokenMockRecorder) Allows(ctx, run, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allows", reflect.TypeOf((*MockRunToken)(nil).Allows), ctx, run, token)
}

// Mint mocks base method.
func (m *MockRunToken) Mint(ctx context.Context, run string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mint", ctx, run)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mint indicates an expected call of Mint.
func (mr *MockRunTokenMockRecorder) Mint(ctx, run any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mint", reflect.TypeOf((*MockRunToken)(nil).Mint), ctx, run)
}

// Release mocks base method.
func (m *MockRunToken) Release(ctx context.Context, run string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release", ctx, run)
}

// Release indicates an expected call of Release.
func (mr *MockRunTokenMockRecorder) Release(ctx, run any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockRunToken)(nil).Release), ctx, run)
}
