// Code generated by MockGen. DO NOT EDIT.
// Source: upload.go
//
// Generated by this command:
//
//	mockgen -source=upload.go -destination=upload/mock_upload.go -package=upload -mock_names=Upload=MockUpload
//

// Package upload is a generated GoMock package.
package upload

import (
	context "context"
	io "io"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUpload is a mock of Upload interface.
type MockUpload struct {
	ctrl     *gomock.Controller
	recorder *MockUploadMockRecorder
	isgomock struct{}
}

// MockUploadMockRecorder is the mock recorder for MockUpload.
type MockUploadMockRecorder struct {
	mock *MockUpload
}

// NewMockUpload creates a new mock instance.
func NewMockUpload(ctrl *gomock.Controller) *MockUpload {
	mock := &MockUpload{ctrl: ctrl}
	mock.recorder = &MockUploadMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpload) EXPECT() *MockUploadMockRecorder {
	return m.recorder
}

// PublishArtifact mocks base method.
func (m *MockUpload) PublishArtifact(ctx context.Context, token, executionID, label string, body io.Reader) (entity.ArtifactReceipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishArtifact", ctx, token, executionID, label, body)
	ret0, _ := ret[0].(entity.ArtifactReceipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishArtifact indicates an expected call of PublishArtifact.
func (mr *MockUploadMockRecorder) PublishArtifact(ctx, token, executionID, label, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishArtifact", reflect.TypeOf((*MockUpload)(nil).PublishArtifact), ctx, token, executionID, label, body)
}
