// Code generated by MockGen. DO NOT EDIT.
// Source: executions.go
//
// Generated by this command:
//
//	mockgen -source=executions.go -destination=execution/mock_executions.go -package=execution -mock_names=Executions=MockExecutions
//

// Package execution is a generated GoMock package.
package execution

import (
	context "context"
	reflect "reflect"

	channelv1 "github.com/usenorn/norn/pkg/channel/v1"
	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutions is a mock of Executions interface.
type MockExecutions struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionsMockRecorder
	isgomock struct{}
}

// MockExecutionsMockRecorder is the mock recorder for MockExecutions.
type MockExecutionsMockRecorder struct {
	mock *MockExecutions
}

// NewMockExecutions creates a new mock instance.
func NewMockExecutions(ctrl *gomock.Controller) *MockExecutions {
	mock := &MockExecutions{ctrl: ctrl}
	mock.recorder = &MockExecutionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutions) EXPECT() *MockExecutionsMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockExecutions) Cancel(ctx context.Context, executionID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, executionID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockExecutionsMockRecorder) Cancel(ctx, executionID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockExecutions)(nil).Cancel), ctx, executionID, reason)
}

// Configure mocks base method.
func (m *MockExecutions) Configure(configuration channelv1.Configuration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Configure", configuration)
}

// Configure indicates an expected call of Configure.
func (mr *MockExecutionsMockRecorder) Configure(configuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockExecutions)(nil).Configure), configuration)
}

// Driver mocks base method.
func (m *MockExecutions) Driver(ctx context.Context) entity.DriverHealth {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Driver", ctx)
	ret0, _ := ret[0].(entity.DriverHealth)
	return ret0
}

// Driver indicates an expected call of Driver.
func (mr *MockExecutionsMockRecorder) Driver(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Driver", reflect.TypeOf((*MockExecutions)(nil).Driver), ctx)
}

// Greeting mocks base method.
func (m *MockExecutions) Greeting() channelv1.Hello {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Greeting")
	ret0, _ := ret[0].(channelv1.Hello)
	return ret0
}

// Greeting indicates an expected call of Greeting.
func (mr *MockExecutionsMockRecorder) Greeting() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Greeting", reflect.TypeOf((*MockExecutions)(nil).Greeting))
}

// List mocks base method.
func (m *MockExecutions) List(ctx context.Context) ([]entity.Execution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockExecutionsMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExecutions)(nil).List), ctx)
}

// Offer mocks base method.
func (m *MockExecutions) Offer(ctx context.Context, offer channelv1.Offer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Offer", ctx, offer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Offer indicates an expected call of Offer.
func (mr *MockExecutionsMockRecorder) Offer(ctx, offer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Offer", reflect.TypeOf((*MockExecutions)(nil).Offer), ctx, offer)
}

// Pause mocks base method.
func (m *MockExecutions) Pause() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Pause")
}

// Pause indicates an expected call of Pause.
func (mr *MockExecutionsMockRecorder) Pause() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockExecutions)(nil).Pause))
}

// Pulse mocks base method.
func (m *MockExecutions) Pulse(ctx context.Context) channelv1.Pulse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pulse", ctx)
	ret0, _ := ret[0].(channelv1.Pulse)
	return ret0
}

// Pulse indicates an expected call of Pulse.
func (mr *MockExecutionsMockRecorder) Pulse(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pulse", reflect.TypeOf((*MockExecutions)(nil).Pulse), ctx)
}

// Reconcile mocks base method.
func (m *MockExecutions) Reconcile(ctx context.Context, leased []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, leased)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockExecutionsMockRecorder) Reconcile(ctx, leased any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockExecutions)(nil).Reconcile), ctx, leased)
}

// Report mocks base method.
func (m *MockExecutions) Report(ctx context.Context) entity.SchedulerReport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report", ctx)
	ret0, _ := ret[0].(entity.SchedulerReport)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MockExecutionsMockRecorder) Report(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockExecutions)(nil).Report), ctx)
}

// Resume mocks base method.
func (m *MockExecutions) Resume() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Resume")
}

// Resume indicates an expected call of Resume.
func (mr *MockExecutionsMockRecorder) Resume() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockExecutions)(nil).Resume))
}

// Run mocks base method.
func (m *MockExecutions) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockExecutionsMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockExecutions)(nil).Run), ctx)
}

// Start mocks base method.
func (m *MockExecutions) Start(ctx context.Context, executionID string, start channelv1.Start) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, executionID, start)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockExecutionsMockRecorder) Start(ctx, executionID, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockExecutions)(nil).Start), ctx, executionID, start)
}

// Timeline mocks base method.
func (m *MockExecutions) Timeline(ctx context.Context, executionID string) ([]entity.TimelineEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timeline", ctx, executionID)
	ret0, _ := ret[0].([]entity.TimelineEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Timeline indicates an expected call of Timeline.
func (mr *MockExecutionsMockRecorder) Timeline(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timeline", reflect.TypeOf((*MockExecutions)(nil).Timeline), ctx, executionID)
}
