// Code generated by MockGen. DO NOT EDIT.
// Source: release.go
//
// Generated by this command:
//
//	mockgen -source=release.go -destination=release/mock_release.go -package=release -mock_names=Release=MockRelease
//

// Package release is a generated GoMock package.
package release

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRelease is a mock of Release interface.
type MockRelease struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseMockRecorder
	isgomock struct{}
}

// MockReleaseMockRecorder is the mock recorder for MockRelease.
type MockReleaseMockRecorder struct {
	mock *MockRelease
}

// NewMockRelease creates a new mock instance.
func NewMockRelease(ctrl *gomock.Controller) *MockRelease {
	mock := &MockRelease{ctrl: ctrl}
	mock.recorder = &MockReleaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelease) EXPECT() *MockReleaseMockRecorder {
	return m.recorder
}

// Latest mocks base method.
func (m *MockRelease) Latest(ctx context.Context) (entity.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Latest", ctx)
	ret0, _ := ret[0].(entity.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Latest indicates an expected call of Latest.
func (mr *MockReleaseMockRecorder) Latest(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Latest", reflect.TypeOf((*MockRelease)(nil).Latest), ctx)
}
