// Code generated by MockGen. DO NOT EDIT.
// Source: process.go
//
// Generated by this command:
//
//	mockgen -source=process.go -destination=process/mock_process.go -package=process -mock_names=Process=MockProcess,Child=MockChild
//

// Package process is a generated GoMock package.
package process

import (
	context "context"
	reflect "reflect"
	time "time"

	repository "github.com/usenorn/runner/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockChild is a mock of Child interface.
type MockChild struct {
	ctrl     *gomock.Controller
	recorder *MockChildMockRecorder
	isgomock struct{}
}

// MockChildMockRecorder is the mock recorder for MockChild.
type MockChildMockRecorder struct {
	mock *MockChild
}

// NewMockChild creates a new mock instance.
func NewMockChild(ctrl *gomock.Controller) *MockChild {
	mock := &MockChild{ctrl: ctrl}
	mock.recorder = &MockChildMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChild) EXPECT() *MockChildMockRecorder {
	return m.recorder
}

// PID mocks base method.
func (m *MockChild) PID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PID")
	ret0, _ := ret[0].(int)
	return ret0
}

// PID indicates an expected call of PID.
func (mr *MockChildMockRecorder) PID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PID", reflect.TypeOf((*MockChild)(nil).PID))
}

// Stop mocks base method.
func (m *MockChild) Stop(ctx context.Context, grace time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, grace)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockChildMockRecorder) Stop(ctx, grace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockChild)(nil).Stop), ctx, grace)
}

// Wait mocks base method.
func (m *MockChild) Wait() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Wait indicates an expected call of Wait.
func (mr *MockChildMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockChild)(nil).Wait))
}

// MockProcess is a mock of Process interface.
type MockProcess struct {
	ctrl     *gomock.Controller
	recorder *MockProcessMockRecorder
	isgomock struct{}
}

// MockProcessMockRecorder is the mock recorder for MockProcess.
type MockProcessMockRecorder struct {
	mock *MockProcess
}

// NewMockProcess creates a new mock instance.
func NewMockProcess(ctrl *gomock.Controller) *MockProcess {
	mock := &MockProcess{ctrl: ctrl}
	mock.recorder = &MockProcessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcess) EXPECT() *MockProcessMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockProcess) Run(ctx context.Context, launch repository.Launch, timeout time.Duration) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, launch, timeout)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockProcessMockRecorder) Run(ctx, launch, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockProcess)(nil).Run), ctx, launch, timeout)
}

// Start mocks base method.
func (m *MockProcess) Start(ctx context.Context, launch repository.Launch) (repository.Child, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, launch)
	ret0, _ := ret[0].(repository.Child)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockProcessMockRecorder) Start(ctx, launch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockProcess)(nil).Start), ctx, launch)
}

// Stray mocks base method.
func (m *MockProcess) Stray(ctx context.Context, pid int, startedAt time.Time) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stray", ctx, pid, startedAt)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Stray indicates an expected call of Stray.
func (mr *MockProcessMockRecorder) Stray(ctx, pid, startedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stray", reflect.TypeOf((*MockProcess)(nil).Stray), ctx, pid, startedAt)
}

// Sweep mocks base method.
func (m *MockProcess) Sweep(ctx context.Context, pid int, grace time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sweep", ctx, pid, grace)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sweep indicates an expected call of Sweep.
func (mr *MockProcessMockRecorder) Sweep(ctx, pid, grace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sweep", reflect.TypeOf((*MockProcess)(nil).Sweep), ctx, pid, grace)
}
