// Code generated by MockGen. DO NOT EDIT.
// Source: snapshots.go
//
// Generated by this command:
//
//	mockgen -source=snapshots.go -destination=snapshot/mock_snapshots.go -package=snapshot -mock_names=Snapshots=MockSnapshots
//

// Package snapshot is a generated GoMock package.
package snapshot

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	service "github.com/usenorn/runner/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSnapshots is a mock of Snapshots interface.
type MockSnapshots struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotsMockRecorder
	isgomock struct{}
}

// MockSnapshotsMockRecorder is the mock recorder for MockSnapshots.
type MockSnapshotsMockRecorder struct {
	mock *MockSnapshots
}

// NewMockSnapshots creates a new mock instance.
func NewMockSnapshots(ctrl *gomock.Controller) *MockSnapshots {
	mock := &MockSnapshots{ctrl: ctrl}
	mock.recorder = &MockSnapshotsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshots) EXPECT() *MockSnapshotsMockRecorder {
	return m.recorder
}

// Discard mocks base method.
func (m *MockSnapshots) Discard(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Discard", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Discard indicates an expected call of Discard.
func (mr *MockSnapshotsMockRecorder) Discard(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Discard", reflect.TypeOf((*MockSnapshots)(nil).Discard), ctx, name)
}

// List mocks base method.
func (m *MockSnapshots) List(ctx context.Context) ([]entity.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSnapshotsMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSnapshots)(nil).List), ctx)
}

// Take mocks base method.
func (m *MockSnapshots) Take(ctx context.Context, request service.TakeRequest) (entity.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Take", ctx, request)
	ret0, _ := ret[0].(entity.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Take indicates an expected call of Take.
func (mr *MockSnapshotsMockRecorder) Take(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Take", reflect.TypeOf((*MockSnapshots)(nil).Take), ctx, request)
}
