// Code generated by MockGen. DO NOT EDIT.
// Source: dashboard.go
//
// Generated by this command:
//
//	mockgen -source=dashboard.go -destination=dashboard/mock_dashboard.go -package=dashboard -mock_names=Dashboard=MockDashboard
//

// Package dashboard is a generated GoMock package.
package dashboard

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	repository "github.com/usenorn/runner/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockDashboard is a mock of Dashboard interface.
type MockDashboard struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardMockRecorder
	isgomock struct{}
}

// MockDashboardMockRecorder is the mock recorder for MockDashboard.
type MockDashboardMockRecorder struct {
	mock *MockDashboard
}

// NewMockDashboard creates a new mock instance.
func NewMockDashboard(ctrl *gomock.Controller) *MockDashboard {
	mock := &MockDashboard{ctrl: ctrl}
	mock.recorder = &MockDashboardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboard) EXPECT() *MockDashboardMockRecorder {
	return m.recorder
}

// Enrol mocks base method.
func (m *MockDashboard) Enrol(ctx context.Context, token string, enrolment repository.Enrolment) (repository.Enrolled, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enrol", ctx, token, enrolment)
	ret0, _ := ret[0].(repository.Enrolled)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enrol indicates an expected call of Enrol.
func (mr *MockDashboardMockRecorder) Enrol(ctx, token, enrolment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enrol", reflect.TypeOf((*MockDashboard)(nil).Enrol), ctx, token, enrolment)
}

// Exchange mocks base method.
func (m *MockDashboard) Exchange(ctx context.Context, refreshToken string, assertion entity.Assertion, signature string) (entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exchange", ctx, refreshToken, assertion, signature)
	ret0, _ := ret[0].(entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exchange indicates an expected call of Exchange.
func (mr *MockDashboardMockRecorder) Exchange(ctx, refreshToken, assertion, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exchange", reflect.TypeOf((*MockDashboard)(nil).Exchange), ctx, refreshToken, assertion, signature)
}
