// Code generated by MockGen. DO NOT EDIT.
// Source: updates.go
//
// Generated by this command:
//
//	mockgen -source=updates.go -destination=update/mock_updates.go -package=update -mock_names=Updates=MockUpdates
//

// Package update is a generated GoMock package.
package update

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdates is a mock of Updates interface.
type MockUpdates struct {
	ctrl     *gomock.Controller
	recorder *MockUpdatesMockRecorder
	isgomock struct{}
}

// MockUpdatesMockRecorder is the mock recorder for MockUpdates.
type MockUpdatesMockRecorder struct {
	mock *MockUpdates
}

// NewMockUpdates creates a new mock instance.
func NewMockUpdates(ctrl *gomock.Controller) *MockUpdates {
	mock := &MockUpdates{ctrl: ctrl}
	mock.recorder = &MockUpdatesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdates) EXPECT() *MockUpdatesMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockUpdates) Check(ctx context.Context) entity.Update {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(entity.Update)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockUpdatesMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockUpdates)(nil).Check), ctx)
}

// Report mocks base method.
func (m *MockUpdates) Report() entity.Update {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report")
	ret0, _ := ret[0].(entity.Update)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MockUpdatesMockRecorder) Report() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockUpdates)(nil).Report))
}

// Run mocks base method.
func (m *MockUpdates) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockUpdatesMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockUpdates)(nil).Run), ctx)
}
