// Code generated by MockGen. DO NOT EDIT.
// Source: scheduling.go
//
// Generated by this command:
//
//	mockgen -source=scheduling.go -destination=scheduling/mock_scheduling.go -package=scheduling -mock_names=Scheduling=MockScheduling
//

// Package scheduling is a generated GoMock package.
package scheduling

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockScheduling is a mock of Scheduling interface.
type MockScheduling struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulingMockRecorder
	isgomock struct{}
}

// MockSchedulingMockRecorder is the mock recorder for MockScheduling.
type MockSchedulingMockRecorder struct {
	mock *MockScheduling
}

// NewMockScheduling creates a new mock instance.
func NewMockScheduling(ctrl *gomock.Controller) *MockScheduling {
	mock := &MockScheduling{ctrl: ctrl}
	mock.recorder = &MockSchedulingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduling) EXPECT() *MockSchedulingMockRecorder {
	return m.recorder
}

// Pause mocks base method.
func (m *MockScheduling) Pause(ctx context.Context, paused bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", ctx, paused)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pause indicates an expected call of Pause.
func (mr *MockSchedulingMockRecorder) Pause(ctx, paused any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockScheduling)(nil).Pause), ctx, paused)
}

// Paused mocks base method.
func (m *MockScheduling) Paused(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Paused", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Paused indicates an expected call of Paused.
func (mr *MockSchedulingMockRecorder) Paused(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paused", reflect.TypeOf((*MockScheduling)(nil).Paused), ctx)
}
