// Code generated by MockGen. DO NOT EDIT.
// Source: uploads.go
//
// Generated by this command:
//
//	mockgen -source=uploads.go -destination=upload/mock_uploads.go -package=upload -mock_names=Uploads=MockUploads
//

// Package upload is a generated GoMock package.
package upload

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUploads is a mock of Uploads interface.
type MockUploads struct {
	ctrl     *gomock.Controller
	recorder *MockUploadsMockRecorder
	isgomock struct{}
}

// MockUploadsMockRecorder is the mock recorder for MockUploads.
type MockUploadsMockRecorder struct {
	mock *MockUploads
}

// NewMockUploads creates a new mock instance.
func NewMockUploads(ctrl *gomock.Controller) *MockUploads {
	mock := &MockUploads{ctrl: ctrl}
	mock.recorder = &MockUploadsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploads) EXPECT() *MockUploadsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockUploads) Close(ctx context.Context, executionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", ctx, executionID)
}

// Close indicates an expected call of Close.
func (mr *MockUploadsMockRecorder) Close(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockUploads)(nil).Close), ctx, executionID)
}

// Event mocks base method.
func (m *MockUploads) Event(ctx context.Context, executionID string, event entity.DriverEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Event", ctx, executionID, event)
}

// Event indicates an expected call of Event.
func (mr *MockUploadsMockRecorder) Event(ctx, executionID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Event", reflect.TypeOf((*MockUploads)(nil).Event), ctx, executionID, event)
}

// Flush mocks base method.
func (m *MockUploads) Flush(ctx context.Context, executionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx, executionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockUploadsMockRecorder) Flush(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockUploads)(nil).Flush), ctx, executionID)
}

// Line mocks base method.
func (m *MockUploads) Line(ctx context.Context, executionID string, line entity.LogLine) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Line", ctx, executionID, line)
}

// Line indicates an expected call of Line.
func (mr *MockUploadsMockRecorder) Line(ctx, executionID, line any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Line", reflect.TypeOf((*MockUploads)(nil).Line), ctx, executionID, line)
}

// Open mocks base method.
func (m *MockUploads) Open(ctx context.Context, executionID string) (entity.TelemetryMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, executionID)
	ret0, _ := ret[0].(entity.TelemetryMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockUploadsMockRecorder) Open(ctx, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockUploads)(nil).Open), ctx, executionID)
}

// Run mocks base method.
func (m *MockUploads) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockUploadsMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockUploads)(nil).Run), ctx)
}
