// Code generated by MockGen. DO NOT EDIT.
// Source: uploads.go
//
// Generated by this command:
//
//	mockgen -source=uploads.go -destination=upload/mock_uploads.go -package=upload -mock_names=Uploads=MockUploads
//

// Package upload is a generated GoMock package.
package upload

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUploads is a mock of Uploads interface.
type MockUploads struct {
	ctrl     *gomock.Controller
	recorder *MockUploadsMockRecorder
	isgomock struct{}
}

// MockUploadsMockRecorder is the mock recorder for MockUploads.
type MockUploadsMockRecorder struct {
	mock *MockUploads
}

// NewMockUploads creates a new mock instance.
func NewMockUploads(ctrl *gomock.Controller) *MockUploads {
	mock := &MockUploads{ctrl: ctrl}
	mock.recorder = &MockUploadsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploads) EXPECT() *MockUploadsMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockUploads) Attach(ctx context.Context, executionID, label string, body []byte) (entity.ArtifactReceipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, executionID, label, body)
	ret0, _ := ret[0].(entity.ArtifactReceipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attach indicates an expected call of Attach.
func (mr *MockUploadsMockRecorder) Attach(ctx, executionID, label, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockUploads)(nil).Attach), ctx, executionID, label, body)
}

// Publish mocks base method.
func (m *MockUploads) Publish(ctx context.Context, executionID string, artifact entity.Artifact) (entity.ArtifactReceipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, executionID, artifact)
	ret0, _ := ret[0].(entity.ArtifactReceipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockUploadsMockRecorder) Publish(ctx, executionID, artifact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockUploads)(nil).Publish), ctx, executionID, artifact)
}
