// Code generated by MockGen. DO NOT EDIT.
// Source: channels.go
//
// Generated by this command:
//
//	mockgen -source=channels.go -destination=channel/mock_channels.go -package=channel -mock_names=Channels=MockChannels
//

// Package channel is a generated GoMock package.
package channel

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockChannels is a mock of Channels interface.
type MockChannels struct {
	ctrl     *gomock.Controller
	recorder *MockChannelsMockRecorder
	isgomock struct{}
}

// MockChannelsMockRecorder is the mock recorder for MockChannels.
type MockChannelsMockRecorder struct {
	mock *MockChannels
}

// NewMockChannels creates a new mock instance.
func NewMockChannels(ctrl *gomock.Controller) *MockChannels {
	mock := &MockChannels{ctrl: ctrl}
	mock.recorder = &MockChannelsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannels) EXPECT() *MockChannelsMockRecorder {
	return m.recorder
}

// Report mocks base method.
func (m *MockChannels) Report(ctx context.Context) entity.ChannelReport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report", ctx)
	ret0, _ := ret[0].(entity.ChannelReport)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MockChannelsMockRecorder) Report(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockChannels)(nil).Report), ctx)
}

// Run mocks base method.
func (m *MockChannels) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockChannelsMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockChannels)(nil).Run), ctx)
}

// Wake mocks base method.
func (m *MockChannels) Wake() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Wake")
}

// Wake indicates an expected call of Wake.
func (mr *MockChannelsMockRecorder) Wake() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wake", reflect.TypeOf((*MockChannels)(nil).Wake))
}
