// Code generated by MockGen. DO NOT EDIT.
// Source: spool.go
//
// Generated by this command:
//
//	mockgen -source=spool.go -destination=spool/mock_spool.go -package=spool -mock_names=Spool=MockSpool
//

// Package spool is a generated GoMock package.
package spool

import (
	context "context"
	reflect "reflect"
	time "time"

	channelv1 "github.com/usenorn/norn/pkg/channel/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockSpool is a mock of Spool interface.
type MockSpool struct {
	ctrl     *gomock.Controller
	recorder *MockSpoolMockRecorder
	isgomock struct{}
}

// MockSpoolMockRecorder is the mock recorder for MockSpool.
type MockSpoolMockRecorder struct {
	mock *MockSpool
}

// NewMockSpool creates a new mock instance.
func NewMockSpool(ctrl *gomock.Controller) *MockSpool {
	mock := &MockSpool{ctrl: ctrl}
	mock.recorder = &MockSpoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpool) EXPECT() *MockSpoolMockRecorder {
	return m.recorder
}

// Acknowledge mocks base method.
func (m *MockSpool) Acknowledge(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acknowledge", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Acknowledge indicates an expected call of Acknowledge.
func (mr *MockSpoolMockRecorder) Acknowledge(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acknowledge", reflect.TypeOf((*MockSpool)(nil).Acknowledge), ctx, id)
}

// Append mocks base method.
func (m *MockSpool) Append(ctx context.Context, message channelv1.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockSpoolMockRecorder) Append(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockSpool)(nil).Append), ctx, message)
}

// Count mocks base method.
func (m *MockSpool) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockSpoolMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockSpool)(nil).Count), ctx)
}

// Head mocks base method.
func (m *MockSpool) Head(ctx context.Context, limit int) ([]channelv1.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Head", ctx, limit)
	ret0, _ := ret[0].([]channelv1.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Head indicates an expected call of Head.
func (mr *MockSpoolMockRecorder) Head(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Head", reflect.TypeOf((*MockSpool)(nil).Head), ctx, limit)
}

// Prune mocks base method.
func (m *MockSpool) Prune(ctx context.Context, before time.Time, keep int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", ctx, before, keep)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prune indicates an expected call of Prune.
func (mr *MockSpoolMockRecorder) Prune(ctx, before, keep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockSpool)(nil).Prune), ctx, before, keep)
}
