// Code generated by MockGen. DO NOT EDIT.
// Source: driver.go
//
// Generated by this command:
//
//	mockgen -source=driver.go -destination=driver/mock_driver.go -package=driver -mock_names=Driver=MockDriver,Session=MockSession
//

// Package driver is a generated GoMock package.
package driver

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/usenorn/runner/internal/entity"
	repository "github.com/usenorn/runner/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// Events mocks base method.
func (m *MockSession) Events() <-chan entity.DriverEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events")
	ret0, _ := ret[0].(<-chan entity.DriverEvent)
	return ret0
}

// Events indicates an expected call of Events.
func (mr *MockSessionMockRecorder) Events() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockSession)(nil).Events))
}

// Logs mocks base method.
func (m *MockSession) Logs() <-chan string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs")
	ret0, _ := ret[0].(<-chan string)
	return ret0
}

// Logs indicates an expected call of Logs.
func (mr *MockSessionMockRecorder) Logs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockSession)(nil).Logs))
}

// Reference mocks base method.
func (m *MockSession) Reference() entity.DriverSession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reference")
	ret0, _ := ret[0].(entity.DriverSession)
	return ret0
}

// Reference indicates an expected call of Reference.
func (mr *MockSessionMockRecorder) Reference() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reference", reflect.TypeOf((*MockSession)(nil).Reference))
}

// Stop mocks base method.
func (m *MockSession) Stop(ctx context.Context, grace time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, grace)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSessionMockRecorder) Stop(ctx, grace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSession)(nil).Stop), ctx, grace)
}

// Wait mocks base method.
func (m *MockSession) Wait() (entity.DriverResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(entity.DriverResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Wait indicates an expected call of Wait.
func (mr *MockSessionMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockSession)(nil).Wait))
}

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
	isgomock struct{}
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// Preflight mocks base method.
func (m *MockDriver) Preflight(ctx context.Context, kind entity.DriverKind) entity.DriverHealth {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preflight", ctx, kind)
	ret0, _ := ret[0].(entity.DriverHealth)
	return ret0
}

// Preflight indicates an expected call of Preflight.
func (mr *MockDriverMockRecorder) Preflight(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preflight", reflect.TypeOf((*MockDriver)(nil).Preflight), ctx, kind)
}

// Resume mocks base method.
func (m *MockDriver) Resume(ctx context.Context, env entity.ExecEnv, held entity.DriverSession, injection string) (repository.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", ctx, env, held, injection)
	ret0, _ := ret[0].(repository.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resume indicates an expected call of Resume.
func (mr *MockDriverMockRecorder) Resume(ctx, env, held, injection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockDriver)(nil).Resume), ctx, env, held, injection)
}

// Start mocks base method.
func (m *MockDriver) Start(ctx context.Context, env entity.ExecEnv, task entity.Task) (repository.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, env, task)
	ret0, _ := ret[0].(repository.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockDriverMockRecorder) Start(ctx, env, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockDriver)(nil).Start), ctx, env, task)
}
