// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/goforj/wire"
	"github.com/usenorn/runner/internal/config"
	"github.com/usenorn/runner/internal/control"
	"github.com/usenorn/runner/internal/observability/logging"
	"github.com/usenorn/runner/internal/pkg/dashboardclient"
	"github.com/usenorn/runner/internal/pkg/hostfacts"
	"github.com/usenorn/runner/internal/pkg/servicemanager"
	"github.com/usenorn/runner/internal/pkg/socket"
	"github.com/usenorn/runner/internal/pkg/statedir"
	"github.com/usenorn/runner/internal/repository/credential"
	"github.com/usenorn/runner/internal/repository/dashboard"
	"github.com/usenorn/runner/internal/repository/identity"
	"github.com/usenorn/runner/internal/service/enrolment"
	"github.com/usenorn/runner/internal/service/session"
	"net/http"
)

// Injectors from wire.go:

func InitDaemon(cfgFile string, overrides config.Overrides) (*Daemon, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configControl := config.NewControl(configConfig)
	runner := config.NewRunner(configConfig)
	state := config.NewState(configConfig)
	app := config.NewApp(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	configSession := config.NewSession(configConfig)
	client, err := dashboardclient.New(runner, configSession, app)
	if err != nil {
		return nil, nil, err
	}
	repositoryDashboard := dashboard.New(client, runner)
	repositoryIdentity := identity.New(dir)
	repositoryCredential := credential.New(dir)
	sessions := session.New(repositoryDashboard, repositoryIdentity, repositoryCredential, configSession)
	host, err := hostfacts.New(app)
	if err != nil {
		return nil, nil, err
	}
	enrolments := enrolment.New(repositoryDashboard, repositoryIdentity, repositoryCredential, sessions, host)
	server := control.NewServer(runner, state, app, dir, enrolments, sessions)
	listener, cleanup, err := socket.New(dir)
	if err != nil {
		return nil, nil, err
	}
	log := config.NewLog(configConfig)
	logger, cleanup2, err := logging.New(app, log, dir)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	daemon := NewDaemon(configControl, server, listener, sessions, logger)
	return daemon, func() {
		cleanup2()
		cleanup()
	}, nil
}

func InitStatus(cfgFile string, overrides config.Overrides) (*Status, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configControl := config.NewControl(configConfig)
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	client := control.NewClient(configControl, dir)
	status := NewStatus(client)
	return status, func() {
	}, nil
}

func InitBinding(cfgFile string, overrides config.Overrides) (*Binding, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configControl := config.NewControl(configConfig)
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	client := control.NewClient(configControl, dir)
	binding := NewBinding(client)
	return binding, func() {
	}, nil
}

func InitInstaller(cfgFile string, overrides config.Overrides) (*Installer, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	manager := servicemanager.New(dir, state)
	installer := NewInstaller(manager)
	return installer, func() {
	}, nil
}

// wire.go:

var baseSet = wire.NewSet(config.Set, logging.Set, statedir.Set, socket.Set, servicemanager.Set, dashboardclient.Set, hostfacts.Set, identity.Set, credential.Set, dashboard.Set, session.Set, enrolment.Set, control.Set, wire.Bind(new(http.Handler), new(*control.Server)), NewDaemon,
	NewStatus,
	NewBinding,
	NewInstaller,
)
