// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/goforj/wire"
	"github.com/usenorn/runner/internal/config"
	"github.com/usenorn/runner/internal/control"
	"github.com/usenorn/runner/internal/mcpserver"
	"github.com/usenorn/runner/internal/observability/logging"
	"github.com/usenorn/runner/internal/pkg/buildinfo"
	"github.com/usenorn/runner/internal/pkg/dashboardclient"
	"github.com/usenorn/runner/internal/pkg/hostfacts"
	"github.com/usenorn/runner/internal/pkg/servicemanager"
	"github.com/usenorn/runner/internal/pkg/socket"
	"github.com/usenorn/runner/internal/pkg/statedir"
	"github.com/usenorn/runner/internal/repository/capability"
	"github.com/usenorn/runner/internal/repository/channel"
	"github.com/usenorn/runner/internal/repository/credential"
	"github.com/usenorn/runner/internal/repository/dashboard"
	"github.com/usenorn/runner/internal/repository/disk"
	"github.com/usenorn/runner/internal/repository/driver"
	"github.com/usenorn/runner/internal/repository/forge"
	"github.com/usenorn/runner/internal/repository/identity"
	"github.com/usenorn/runner/internal/repository/inventory"
	"github.com/usenorn/runner/internal/repository/materialiser"
	"github.com/usenorn/runner/internal/repository/port"
	"github.com/usenorn/runner/internal/repository/process"
	"github.com/usenorn/runner/internal/repository/release"
	"github.com/usenorn/runner/internal/repository/run"
	"github.com/usenorn/runner/internal/repository/runtoken"
	"github.com/usenorn/runner/internal/repository/scanner"
	"github.com/usenorn/runner/internal/repository/scheduling"
	"github.com/usenorn/runner/internal/repository/servicelog"
	"github.com/usenorn/runner/internal/repository/settings"
	"github.com/usenorn/runner/internal/repository/spool"
	"github.com/usenorn/runner/internal/repository/upload"
	"github.com/usenorn/runner/internal/repository/worktree"
	"github.com/usenorn/runner/internal/service/changeset"
	channel2 "github.com/usenorn/runner/internal/service/channel"
	"github.com/usenorn/runner/internal/service/codebase"
	"github.com/usenorn/runner/internal/service/enrolment"
	"github.com/usenorn/runner/internal/service/execution"
	"github.com/usenorn/runner/internal/service/preview"
	"github.com/usenorn/runner/internal/service/question"
	"github.com/usenorn/runner/internal/service/session"
	"github.com/usenorn/runner/internal/service/snapshot"
	"github.com/usenorn/runner/internal/service/supervisor"
	"github.com/usenorn/runner/internal/service/update"
	upload2 "github.com/usenorn/runner/internal/service/upload"
	"net/http"
)

// Injectors from wire.go:

func InitDaemon(cfgFile string, overrides config.Overrides) (*Daemon, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configControl := config.NewControl(configConfig)
	runner := config.NewRunner(configConfig)
	state := config.NewState(configConfig)
	app := config.NewApp(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	configSession := config.NewSession(configConfig)
	client, err := dashboardclient.New(runner, configSession, app)
	if err != nil {
		return nil, nil, err
	}
	repositoryDashboard := dashboard.New(client, runner)
	repositoryIdentity := identity.New(dir)
	repositoryCredential := credential.New(dir)
	sessions := session.New(repositoryDashboard, repositoryIdentity, repositoryCredential, configSession)
	host, err := hostfacts.New(app)
	if err != nil {
		return nil, nil, err
	}
	enrolments := enrolment.New(repositoryDashboard, repositoryIdentity, repositoryCredential, sessions, host)
	configUpdate := config.NewUpdate(configConfig)
	repositoryRelease := release.New(configUpdate, app)
	build := buildinfo.New(app)
	updates := update.New(repositoryRelease, build, configUpdate)
	configCodebase := config.NewCodebase(configConfig)
	repositoryScanner := scanner.New(configCodebase)
	repositoryCapability := capability.New(configCodebase)
	repositoryInventory := inventory.New(dir)
	codebases := codebase.New(repositoryScanner, repositoryCapability, repositoryInventory, repositoryDashboard, sessions, configCodebase)
	configChannel := config.NewChannel(configConfig)
	repositoryChannel := channel.New(runner, app, configChannel)
	repositorySpool := spool.New(dir)
	repositoryRun := run.New(dir)
	repositoryDisk := disk.New()
	repositoryScheduling := scheduling.New(dir)
	repositorySettings := settings.New()
	configSnapshot := config.NewSnapshot(configConfig)
	results := config.NewResults(configConfig)
	repositoryWorktree := worktree.New(configSnapshot, results)
	repositoryMaterialiser := materialiser.New()
	snapshots := snapshot.New(repositoryWorktree, repositoryMaterialiser, repositorySettings, repositoryInventory, repositoryRun, configSnapshot)
	repositoryProcess := process.New()
	repositoryPort := port.New(runner)
	serviceLog := servicelog.New(dir)
	configSupervisor := config.NewSupervisor(configConfig)
	services := supervisor.New(repositoryProcess, repositoryPort, serviceLog, repositoryRun, repositorySpool, configSupervisor)
	repositoryUpload := upload.New(client, runner)
	configUpload := config.NewUpload(configConfig)
	uploads := upload2.New(repositoryUpload, repositoryRun, repositoryDashboard, sessions, configUpload)
	questions := config.NewQuestions(configConfig)
	serviceQuestions := question.New(repositoryRun, repositorySpool, questions)
	previews := preview.New(repositoryRun, repositorySpool)
	repositoryForge := forge.New(results)
	changeSets := changeset.New(repositoryRun, repositorySpool, repositoryWorktree, repositoryForge, uploads, results)
	runToken := runtoken.New()
	configDriver := config.NewDriver(configConfig)
	repositoryDriver := driver.New(repositoryProcess, configDriver)
	scheduler := config.NewScheduler(configConfig)
	executions := execution.New(repositoryRun, repositorySpool, repositoryDisk, repositoryScheduling, repositorySettings, repositoryInventory, snapshots, services, uploads, serviceQuestions, previews, changeSets, runToken, repositoryDriver, dir, runner, app, scheduler, configDriver)
	configSpool := config.NewSpool(configConfig)
	channels := channel2.New(repositoryChannel, repositorySpool, sessions, executions, serviceQuestions, configChannel, configSpool, app)
	server := control.NewServer(runner, state, app, dir, enrolments, sessions, updates, codebases, channels, executions, services, serviceQuestions, previews, uploads, runToken, build)
	listener, cleanup, err := socket.New(dir)
	if err != nil {
		return nil, nil, err
	}
	log := config.NewLog(configConfig)
	logger, cleanup2, err := logging.New(app, log, dir)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	daemon := NewDaemon(configControl, server, listener, sessions, updates, codebases, channels, executions, services, uploads, logger)
	return daemon, func() {
		cleanup2()
		cleanup()
	}, nil
}

func InitStatus(cfgFile string, overrides config.Overrides) (*Status, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configControl := config.NewControl(configConfig)
	questions := config.NewQuestions(configConfig)
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	bearer := control.NewBearer()
	client := control.NewClient(configControl, questions, dir, bearer)
	status := NewStatus(client)
	return status, func() {
	}, nil
}

func InitVersion(cfgFile string, overrides config.Overrides) (*Version, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configControl := config.NewControl(configConfig)
	questions := config.NewQuestions(configConfig)
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	bearer := control.NewBearer()
	client := control.NewClient(configControl, questions, dir, bearer)
	configUpdate := config.NewUpdate(configConfig)
	app := config.NewApp(configConfig)
	repositoryRelease := release.New(configUpdate, app)
	build := buildinfo.New(app)
	updates := update.New(repositoryRelease, build, configUpdate)
	version := NewVersion(client, updates, build)
	return version, func() {
	}, nil
}

func InitBinding(cfgFile string, overrides config.Overrides) (*Binding, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configControl := config.NewControl(configConfig)
	questions := config.NewQuestions(configConfig)
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	bearer := control.NewBearer()
	client := control.NewClient(configControl, questions, dir, bearer)
	binding := NewBinding(client)
	return binding, func() {
	}, nil
}

func InitInspection(cfgFile string, overrides config.Overrides) (*Inspection, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configControl := config.NewControl(configConfig)
	questions := config.NewQuestions(configConfig)
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	bearer := control.NewBearer()
	client := control.NewClient(configControl, questions, dir, bearer)
	inspection := NewInspection(client)
	return inspection, func() {
	}, nil
}

func InitSnapshotting(cfgFile string, overrides config.Overrides) (*Snapshotting, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configSnapshot := config.NewSnapshot(configConfig)
	results := config.NewResults(configConfig)
	repositoryWorktree := worktree.New(configSnapshot, results)
	repositoryMaterialiser := materialiser.New()
	repositorySettings := settings.New()
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	repositoryInventory := inventory.New(dir)
	repositoryRun := run.New(dir)
	snapshots := snapshot.New(repositoryWorktree, repositoryMaterialiser, repositorySettings, repositoryInventory, repositoryRun, configSnapshot)
	snapshotting := NewSnapshotting(snapshots)
	return snapshotting, func() {
	}, nil
}

func InitScheduling(cfgFile string, overrides config.Overrides) (*Scheduling, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configControl := config.NewControl(configConfig)
	questions := config.NewQuestions(configConfig)
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	bearer := control.NewBearer()
	client := control.NewClient(configControl, questions, dir, bearer)
	internalScheduling := NewScheduling(client)
	return internalScheduling, func() {
	}, nil
}

func InitExecutions(cfgFile string, overrides config.Overrides) (*Executions, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configControl := config.NewControl(configConfig)
	questions := config.NewQuestions(configConfig)
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	bearer := control.NewBearer()
	client := control.NewClient(configControl, questions, dir, bearer)
	executions := NewExecutions(client)
	return executions, func() {
	}, nil
}

func InitServices(cfgFile string, overrides config.Overrides) (*Services, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configControl := config.NewControl(configConfig)
	questions := config.NewQuestions(configConfig)
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	bearer := control.NewBearer()
	client := control.NewClient(configControl, questions, dir, bearer)
	services := NewServices(client)
	return services, func() {
	}, nil
}

func InitInstaller(cfgFile string, overrides config.Overrides) (*Installer, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	manager := servicemanager.New(dir, state)
	installer := NewInstaller(manager)
	return installer, func() {
	}, nil
}

func InitMCPServer(cfgFile string, overrides config.Overrides) (*mcpserver.Server, func(), error) {
	configConfig, err := config.New(cfgFile, overrides)
	if err != nil {
		return nil, nil, err
	}
	configControl := config.NewControl(configConfig)
	questions := config.NewQuestions(configConfig)
	state := config.NewState(configConfig)
	dir, err := statedir.New(state)
	if err != nil {
		return nil, nil, err
	}
	bearer := control.NewBearer()
	client := control.NewClient(configControl, questions, dir, bearer)
	app := config.NewApp(configConfig)
	server := mcpserver.New(client, app)
	return server, func() {
	}, nil
}

// wire.go:

var baseSet = wire.NewSet(config.Set, logging.Set, statedir.Set, socket.Set, servicemanager.Set, dashboardclient.Set, hostfacts.Set, buildinfo.Set, identity.Set, credential.Set, dashboard.Set, release.Set, scanner.Set, capability.Set, inventory.Set, worktree.Set, materialiser.Set, settings.Set, run.Set, scheduling.Set, spool.Set, channel.Set, disk.Set, process.Set, port.Set, servicelog.Set, driver.Set, upload.Set, runtoken.Set, forge.Set, session.Set, enrolment.Set, update.Set, codebase.Set, snapshot.Set, supervisor.Set, upload2.Set, question.Set, preview.Set, changeset.Set, execution.Set, channel2.Set, control.Set, mcpserver.Set, wire.Bind(new(http.Handler), new(*control.Server)), NewDaemon,
	NewStatus,
	NewVersion,
	NewBinding,
	NewInspection,
	NewSnapshotting,
	NewScheduling,
	NewExecutions,
	NewServices,
	NewInstaller,
)
