// Code generated by MockGen. DO NOT EDIT.
// Source: tunnel.go
//
// Generated by this command:
//
//	mockgen -source=tunnel.go -destination=tunnel/mock_tunnel.go -package=tunnel -mock_names=Tunnel=MockTunnel
//

// Package tunnel is a generated GoMock package.
package tunnel

import (
	context "context"
	net "net"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	repository "github.com/usenorn/runner/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockTunnelSession is a mock of TunnelSession interface.
type MockTunnelSession struct {
	ctrl     *gomock.Controller
	recorder *MockTunnelSessionMockRecorder
	isgomock struct{}
}

// MockTunnelSessionMockRecorder is the mock recorder for MockTunnelSession.
type MockTunnelSessionMockRecorder struct {
	mock *MockTunnelSession
}

// NewMockTunnelSession creates a new mock instance.
func NewMockTunnelSession(ctrl *gomock.Controller) *MockTunnelSession {
	mock := &MockTunnelSession{ctrl: ctrl}
	mock.recorder = &MockTunnelSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTunnelSession) EXPECT() *MockTunnelSessionMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockTunnelSession) Accept() (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept")
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accept indicates an expected call of Accept.
func (mr *MockTunnelSessionMockRecorder) Accept() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockTunnelSession)(nil).Accept))
}

// Close mocks base method.
func (m *MockTunnelSession) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTunnelSessionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTunnelSession)(nil).Close))
}

// MockTunnel is a mock of Tunnel interface.
type MockTunnel struct {
	ctrl     *gomock.Controller
	recorder *MockTunnelMockRecorder
	isgomock struct{}
}

// MockTunnelMockRecorder is the mock recorder for MockTunnel.
type MockTunnelMockRecorder struct {
	mock *MockTunnel
}

// NewMockTunnel creates a new mock instance.
func NewMockTunnel(ctrl *gomock.Controller) *MockTunnel {
	mock := &MockTunnel{ctrl: ctrl}
	mock.recorder = &MockTunnelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTunnel) EXPECT() *MockTunnelMockRecorder {
	return m.recorder
}

// Dial mocks base method.
func (m *MockTunnel) Dial(ctx context.Context, ticket entity.TunnelTicket) (repository.TunnelSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", ctx, ticket)
	ret0, _ := ret[0].(repository.TunnelSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockTunnelMockRecorder) Dial(ctx, ticket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockTunnel)(nil).Dial), ctx, ticket)
}
