// Code generated by MockGen. DO NOT EDIT.
// Source: enrolments.go
//
// Generated by this command:
//
//	mockgen -source=enrolments.go -destination=enrolment/mock_enrolments.go -package=enrolment -mock_names=Enrolments=MockEnrolments
//

// Package enrolment is a generated GoMock package.
package enrolment

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	service "github.com/usenorn/runner/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockEnrolments is a mock of Enrolments interface.
type MockEnrolments struct {
	ctrl     *gomock.Controller
	recorder *MockEnrolmentsMockRecorder
	isgomock struct{}
}

// MockEnrolmentsMockRecorder is the mock recorder for MockEnrolments.
type MockEnrolmentsMockRecorder struct {
	mock *MockEnrolments
}

// NewMockEnrolments creates a new mock instance.
func NewMockEnrolments(ctrl *gomock.Controller) *MockEnrolments {
	mock := &MockEnrolments{ctrl: ctrl}
	mock.recorder = &MockEnrolmentsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrolments) EXPECT() *MockEnrolmentsMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockEnrolments) Connect(ctx context.Context, input service.ConnectInput) (service.Connected, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, input)
	ret0, _ := ret[0].(service.Connected)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockEnrolmentsMockRecorder) Connect(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockEnrolments)(nil).Connect), ctx, input)
}

// Current mocks base method.
func (m *MockEnrolments) Current(ctx context.Context) (entity.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current", ctx)
	ret0, _ := ret[0].(entity.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current.
func (mr *MockEnrolmentsMockRecorder) Current(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockEnrolments)(nil).Current), ctx)
}

// Disconnect mocks base method.
func (m *MockEnrolments) Disconnect(ctx context.Context) (entity.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect", ctx)
	ret0, _ := ret[0].(entity.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockEnrolmentsMockRecorder) Disconnect(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockEnrolments)(nil).Disconnect), ctx)
}
