// Code generated by MockGen. DO NOT EDIT.
// Source: credential.go
//
// Generated by this command:
//
//	mockgen -source=credential.go -destination=credential/mock_credential.go -package=credential -mock_names=Credential=MockCredential
//

// Package credential is a generated GoMock package.
package credential

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCredential is a mock of Credential interface.
type MockCredential struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialMockRecorder
	isgomock struct{}
}

// MockCredentialMockRecorder is the mock recorder for MockCredential.
type MockCredentialMockRecorder struct {
	mock *MockCredential
}

// NewMockCredential creates a new mock instance.
func NewMockCredential(ctrl *gomock.Controller) *MockCredential {
	mock := &MockCredential{ctrl: ctrl}
	mock.recorder = &MockCredentialMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredential) EXPECT() *MockCredentialMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockCredential) Clear(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockCredentialMockRecorder) Clear(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockCredential)(nil).Clear), ctx)
}

// Load mocks base method.
func (m *MockCredential) Load(ctx context.Context, store entity.Store) (entity.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, store)
	ret0, _ := ret[0].(entity.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockCredentialMockRecorder) Load(ctx, store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockCredential)(nil).Load), ctx, store)
}

// LoadAgentToken mocks base method.
func (m *MockCredential) LoadAgentToken(ctx context.Context, store entity.Store) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAgentToken", ctx, store)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAgentToken indicates an expected call of LoadAgentToken.
func (mr *MockCredentialMockRecorder) LoadAgentToken(ctx, store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAgentToken", reflect.TypeOf((*MockCredential)(nil).LoadAgentToken), ctx, store)
}

// Save mocks base method.
func (m *MockCredential) Save(ctx context.Context, store entity.Store, credentials entity.Credentials) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, store, credentials)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCredentialMockRecorder) Save(ctx, store, credentials any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCredential)(nil).Save), ctx, store, credentials)
}

// SaveAgentToken mocks base method.
func (m *MockCredential) SaveAgentToken(ctx context.Context, store entity.Store, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAgentToken", ctx, store, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAgentToken indicates an expected call of SaveAgentToken.
func (mr *MockCredentialMockRecorder) SaveAgentToken(ctx, store, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAgentToken", reflect.TypeOf((*MockCredential)(nil).SaveAgentToken), ctx, store, token)
}

// Usable mocks base method.
func (m *MockCredential) Usable(ctx context.Context, store entity.Store) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usable", ctx, store)
	ret0, _ := ret[0].(error)
	return ret0
}

// Usable indicates an expected call of Usable.
func (mr *MockCredentialMockRecorder) Usable(ctx, store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usable", reflect.TypeOf((*MockCredential)(nil).Usable), ctx, store)
}
