// Code generated by MockGen. DO NOT EDIT.
// Source: tunnels.go
//
// Generated by this command:
//
//	mockgen -source=tunnels.go -destination=tunnel/mock_tunnels.go -package=tunnel -mock_names=Tunnels=MockTunnels
//

// Package tunnel is a generated GoMock package.
package tunnel

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTunnels is a mock of Tunnels interface.
type MockTunnels struct {
	ctrl     *gomock.Controller
	recorder *MockTunnelsMockRecorder
	isgomock struct{}
}

// MockTunnelsMockRecorder is the mock recorder for MockTunnels.
type MockTunnelsMockRecorder struct {
	mock *MockTunnels
}

// NewMockTunnels creates a new mock instance.
func NewMockTunnels(ctrl *gomock.Controller) *MockTunnels {
	mock := &MockTunnels{ctrl: ctrl}
	mock.recorder = &MockTunnelsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTunnels) EXPECT() *MockTunnelsMockRecorder {
	return m.recorder
}

// Report mocks base method.
func (m *MockTunnels) Report() entity.TunnelReport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report")
	ret0, _ := ret[0].(entity.TunnelReport)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MockTunnelsMockRecorder) Report() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockTunnels)(nil).Report))
}

// Run mocks base method.
func (m *MockTunnels) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockTunnelsMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTunnels)(nil).Run), ctx)
}

// Wake mocks base method.
func (m *MockTunnels) Wake() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Wake")
}

// Wake indicates an expected call of Wake.
func (mr *MockTunnelsMockRecorder) Wake() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wake", reflect.TypeOf((*MockTunnels)(nil).Wake))
}
