// Code generated by MockGen. DO NOT EDIT.
// Source: capability.go
//
// Generated by this command:
//
//	mockgen -source=capability.go -destination=capability/mock_capability.go -package=capability -mock_names=Capability=MockCapability
//

// Package capability is a generated GoMock package.
package capability

import (
	context "context"
	reflect "reflect"

	repository "github.com/usenorn/runner/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockCapability is a mock of Capability interface.
type MockCapability struct {
	ctrl     *gomock.Controller
	recorder *MockCapabilityMockRecorder
	isgomock struct{}
}

// MockCapabilityMockRecorder is the mock recorder for MockCapability.
type MockCapabilityMockRecorder struct {
	mock *MockCapability
}

// NewMockCapability creates a new mock instance.
func NewMockCapability(ctrl *gomock.Controller) *MockCapability {
	mock := &MockCapability{ctrl: ctrl}
	mock.recorder = &MockCapabilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapability) EXPECT() *MockCapabilityMockRecorder {
	return m.recorder
}

// Detect mocks base method.
func (m *MockCapability) Detect(ctx context.Context, gateway string) repository.Capabilities {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detect", ctx, gateway)
	ret0, _ := ret[0].(repository.Capabilities)
	return ret0
}

// Detect indicates an expected call of Detect.
func (mr *MockCapabilityMockRecorder) Detect(ctx, gateway any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detect", reflect.TypeOf((*MockCapability)(nil).Detect), ctx, gateway)
}
