name: pull-request

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    permissions:
      contents: read
    uses: ./.github/workflows/checks.yml
