name: pull-request

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  runner:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      - name: Lint
        run: go tool golangci-lint run

      - name: Vulnerabilities
        run: go tool govulncheck ./...
