// Code generated by MockGen. DO NOT EDIT.
// Source: run.go
//
// Generated by this command:
//
//	mockgen -source=run.go -destination=run/mock_run.go -package=run -mock_names=Run=MockRun
//

// Package run is a generated GoMock package.
package run

import (
	context "context"
	reflect "reflect"

	entity "github.com/usenorn/runner/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRun is a mock of Run interface.
type MockRun struct {
	ctrl     *gomock.Controller
	recorder *MockRunMockRecorder
	isgomock struct{}
}

// MockRunMockRecorder is the mock recorder for MockRun.
type MockRunMockRecorder struct {
	mock *MockRun
}

// NewMockRun creates a new mock instance.
func NewMockRun(ctrl *gomock.Controller) *MockRun {
	mock := &MockRun{ctrl: ctrl}
	mock.recorder = &MockRunMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRun) EXPECT() *MockRunMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockRun) Append(ctx context.Context, name string, entry entity.TimelineEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, name, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockRunMockRecorder) Append(ctx, name, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockRun)(nil).Append), ctx, name, entry)
}

// List mocks base method.
func (m *MockRun) List(ctx context.Context) ([]entity.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRunMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRun)(nil).List), ctx)
}

// Load mocks base method.
func (m *MockRun) Load(ctx context.Context, name string) (entity.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, name)
	ret0, _ := ret[0].(entity.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockRunMockRecorder) Load(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockRun)(nil).Load), ctx, name)
}

// LoadDriver mocks base method.
func (m *MockRun) LoadDriver(ctx context.Context, name string) (entity.RunDriver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadDriver", ctx, name)
	ret0, _ := ret[0].(entity.RunDriver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadDriver indicates an expected call of LoadDriver.
func (mr *MockRunMockRecorder) LoadDriver(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadDriver", reflect.TypeOf((*MockRun)(nil).LoadDriver), ctx, name)
}

// LoadServices mocks base method.
func (m *MockRun) LoadServices(ctx context.Context, name string) (entity.RunServices, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadServices", ctx, name)
	ret0, _ := ret[0].(entity.RunServices)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadServices indicates an expected call of LoadServices.
func (mr *MockRunMockRecorder) LoadServices(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadServices", reflect.TypeOf((*MockRun)(nil).LoadServices), ctx, name)
}

// LoadSetup mocks base method.
func (m *MockRun) LoadSetup(ctx context.Context, name string) (entity.RunSetup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSetup", ctx, name)
	ret0, _ := ret[0].(entity.RunSetup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSetup indicates an expected call of LoadSetup.
func (mr *MockRunMockRecorder) LoadSetup(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSetup", reflect.TypeOf((*MockRun)(nil).LoadSetup), ctx, name)
}

// LoadTask mocks base method.
func (m *MockRun) LoadTask(ctx context.Context, name string) (entity.Execution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTask", ctx, name)
	ret0, _ := ret[0].(entity.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadTask indicates an expected call of LoadTask.
func (mr *MockRunMockRecorder) LoadTask(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTask", reflect.TypeOf((*MockRun)(nil).LoadTask), ctx, name)
}

// LoadTasks mocks base method.
func (m *MockRun) LoadTasks(ctx context.Context) ([]entity.Execution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTasks", ctx)
	ret0, _ := ret[0].([]entity.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadTasks indicates an expected call of LoadTasks.
func (mr *MockRunMockRecorder) LoadTasks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTasks", reflect.TypeOf((*MockRun)(nil).LoadTasks), ctx)
}

// Open mocks base method.
func (m *MockRun) Open(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockRunMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockRun)(nil).Open), ctx, name)
}

// Prepare mocks base method.
func (m *MockRun) Prepare(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prepare indicates an expected call of Prepare.
func (mr *MockRunMockRecorder) Prepare(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockRun)(nil).Prepare), ctx, name)
}

// Prune mocks base method.
func (m *MockRun) Prune(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prune indicates an expected call of Prune.
func (mr *MockRunMockRecorder) Prune(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockRun)(nil).Prune), ctx, name)
}

// Remove mocks base method.
func (m *MockRun) Remove(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRunMockRecorder) Remove(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRun)(nil).Remove), ctx, name)
}

// Retire mocks base method.
func (m *MockRun) Retire(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retire", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Retire indicates an expected call of Retire.
func (mr *MockRunMockRecorder) Retire(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retire", reflect.TypeOf((*MockRun)(nil).Retire), ctx, name)
}

// Save mocks base method.
func (m *MockRun) Save(ctx context.Context, snapshot entity.Snapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, snapshot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRunMockRecorder) Save(ctx, snapshot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRun)(nil).Save), ctx, snapshot)
}

// SaveDriver mocks base method.
func (m *MockRun) SaveDriver(ctx context.Context, name string, driver entity.RunDriver) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDriver", ctx, name, driver)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDriver indicates an expected call of SaveDriver.
func (mr *MockRunMockRecorder) SaveDriver(ctx, name, driver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDriver", reflect.TypeOf((*MockRun)(nil).SaveDriver), ctx, name, driver)
}

// SaveServices mocks base method.
func (m *MockRun) SaveServices(ctx context.Context, name string, services entity.RunServices) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveServices", ctx, name, services)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveServices indicates an expected call of SaveServices.
func (mr *MockRunMockRecorder) SaveServices(ctx, name, services any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveServices", reflect.TypeOf((*MockRun)(nil).SaveServices), ctx, name, services)
}

// SaveSetup mocks base method.
func (m *MockRun) SaveSetup(ctx context.Context, name string, setup entity.RunSetup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSetup", ctx, name, setup)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSetup indicates an expected call of SaveSetup.
func (mr *MockRunMockRecorder) SaveSetup(ctx, name, setup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSetup", reflect.TypeOf((*MockRun)(nil).SaveSetup), ctx, name, setup)
}

// SaveTask mocks base method.
func (m *MockRun) SaveTask(ctx context.Context, execution entity.Execution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTask", ctx, execution)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTask indicates an expected call of SaveTask.
func (mr *MockRunMockRecorder) SaveTask(ctx, execution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTask", reflect.TypeOf((*MockRun)(nil).SaveTask), ctx, execution)
}

// Timeline mocks base method.
func (m *MockRun) Timeline(ctx context.Context, name string) ([]entity.TimelineEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timeline", ctx, name)
	ret0, _ := ret[0].([]entity.TimelineEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Timeline indicates an expected call of Timeline.
func (mr *MockRunMockRecorder) Timeline(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timeline", reflect.TypeOf((*MockRun)(nil).Timeline), ctx, name)
}

// Usage mocks base method.
func (m *MockRun) Usage(ctx context.Context) ([]entity.RunUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usage", ctx)
	ret0, _ := ret[0].([]entity.RunUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Usage indicates an expected call of Usage.
func (mr *MockRunMockRecorder) Usage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usage", reflect.TypeOf((*MockRun)(nil).Usage), ctx)
}
